university_pilot_list_duo=[#value in database, label displayed
                       ('Xiamen University','厦门大学'),
                       ('Suzhou University','苏州大学'),
                       ('Zhongshan University','中山大学'),
                       ('Fudan University','复旦大学'),
                       ('Nankai University','南开大学'),
                       ('Peking University','北京大学'),
                       ('Langzhou Univesity','兰州大学'),
                       ('Hunan University','湖南大学'),
                       ('Southwest University','西南大学'),
                       ('Sichuan University','四川大学'),
                       ('Jilin University','吉林大学'),
                       ('Zhejiang University','浙江大学'),
                       ('Wuhan University','武汉大学'),
                       ('Shandong University','山东大学'),
                       ('University of Science and Technology of China','中国科学技术大学')
                       ]
university_pilot_list_duo_round2=[
    ('Anhui University', '安徽大学'),
    ('Beijing Normal University', '北京师范大学'),
    ('Central China Normal University', '华中师范大学'),
    ('Central South University', '中南大学'),
    ('Central University of Finance and Economics', '中央财经大学'),
    ('Chongqing University', '重庆大学'),
    ('Donghua University', '东华大学'),
    ('East China Normal University', '华东师范大学'),
    # ('Fudan University', '复旦大学'),
    ('Fuzhou University', '福州大学'),
    ('Guangxi University', '广西大学'),
    ('Guizhou University', '贵州大学'),
    ('Hainan University', '海南大学'),
    ('Harbin Institute of Technology', '哈尔滨工业大学'),
    ('Huazhong University of Science and Technology', '华中科技大学'),
    # ('Hunan University', '湖南大学'),
    ('Inner Mongolia University', '内蒙古大学'),
    ('Jiangnan University', '江南大学'),
    # ('Jilin University', '吉林大学'),
    ('Jinan University', '暨南大学'),
    # ('Lanzhou University', '兰州大学'),
    ('Liaoning University', '辽宁大学'),
    ('Nanchang University', '南昌大学'),
    ('Nanjing Normal University', '南京师范大学'),
    ('Nanjing University', '南京大学'),
    # ('Nankai University', '南开大学'),
    ('Ningxia University', '宁夏大学'),
    ('Northeastern University (China)', '东北大学'),
    ('Northwest University (China)', '西北大学'),
    ('Ocean University of China', '中国海洋大学'),
    # ('Peking University', '北京大学'),
    ('Qinghai University', '青海大学'),
    ('Renmin University of China', '中国人民大学'),
    ('Shanghai Jiao Tong University', '上海交通大学'),
    ('Shanghai University', '上海大学'),
    ('Shanghai University of Finance and Economics', '上海财经大学'),
    ('ShanghaiTech University', '上海科技大学'),
    # ('Shandong University', '山东大学'),
    ('Shihezi University', '石河子大学'),
    # ('Sichuan University', '四川大学'),
    ('Southeast University', '东南大学'),
    ('Southwestern University of Finance and Economics', '西南财经大学'),
    # ('Sun Yat-sen University', '中山大学'),
    # ('Suzhou University', '苏州大学'),
    ('Tianjin University', '天津大学'),
    ('Tibet University', '西藏大学'),
    ('Tongji University', '同济大学'),
    ('Tsinghua University', '清华大学'),
    ('University of International Business and Economics', '对外经济贸易大学'),
    # ('University of Science and Technology of China', '中国科学技术大学'),
    # ('Wuhan University', '武汉大学'),
    ('Xi\'an Jiaotong University', '西安交通大学'),
    # ('Xiamen University', '厦门大学'),
    ('Xinjiang University', '新疆大学'),
    ('Yanbian University', '延边大学'),
    ('Yunnan University', '云南大学'),
    # ('Zhejiang University', '浙江大学'),
    ('Zhengzhou University', '郑州大学'),
    ('Zhongnan University of Economics and Law', '中南财经政法大学'),
]


university_pilot_list=[]
for (en,cn) in university_pilot_list_duo_round2: #university_pilot_list_duo:
    university_pilot_list.append((cn,cn))

# university_pilot_list
