# Generated by Django 4.1.7 on 2023-03-30 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0002_userinput"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinput", old_name="data", new_name="note",
        ),
        migrations.RemoveField(model_name="userinput", name="email",),
        migrations.RemoveField(model_name="userinput", name="phone",),
        migrations.AddField(
            model_name="userinput",
            name="end_year_mon",
            field=models.CharField(
                default="0000",
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        message="Only xxxx or xxxx-xx are allowed.",
                        regex="^[0-9]{4}(\\-[0-9]{2}){0,1}$",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="school",
            field=models.CharField(default="na", max_length=50),
        ),
        migrations.AddField(
            model_name="userinput",
            name="st_year_mon",
            field=models.CharField(
                default="0000",
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        message="Only xxxx or xxxx-xx are allowed.",
                        regex="^[0-9]{4}(\\-[0-9]{2}){0,1}$",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="university",
            field=models.CharField(default="na", max_length=50),
        ),
        migrations.AlterField(
            model_name="userinput", name="name", field=models.CharField(max_length=20),
        ),
    ]
