# Generated by Django 4.1.7 on 2023-04-04 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0003_rename_data_userinput_note_remove_userinput_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeanInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(default="na", max_length=50)),
                ("university_en", models.CharField(default="na", max_length=50)),
                ("school", models.CharField(default="na", max_length=50)),
                ("school_en", models.CharField(default="na", max_length=50)),
                ("school_class", models.CharField(default="na", max_length=50)),
                ("name", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("is_name_common", models.CharField(max_length=20)),
                (
                    "st_year_mon",
                    models.CharField(
                        default="0000",
                        max_length=7,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.RegexValidator(
                                message="Only xxxx or xxxx-xx are allowed.",
                                regex="^[0-9]{4}(\\-[0-9]{2}){0,1}$",
                            ),
                        ],
                    ),
                ),
                (
                    "end_year_mon",
                    models.CharField(
                        default="0000",
                        max_length=7,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.RegexValidator(
                                message="Only xxxx or xxxx-xx are allowed.",
                                regex="^[0-9]{4}(\\-[0-9]{2}){0,1}$",
                            ),
                        ],
                    ),
                ),
                ("institution_phd_graduation", models.CharField(max_length=20)),
                ("country_phd_graduation", models.CharField(max_length=20)),
                ("year_phd_graduation", models.CharField(max_length=20)),
                ("year_phd_graduation_info_url", models.CharField(max_length=20)),
                ("scopus_auid", models.CharField(max_length=20)),
                ("scopus_auprofile_url", models.CharField(max_length=20)),
                ("scopus_h_index_till_2022", models.CharField(max_length=20)),
                ("OCRID", models.CharField(max_length=20)),
                ("WF_scholar_id", models.CharField(max_length=20)),
                ("WF_h_index_till_2022", models.CharField(max_length=20)),
                ("CV_string", models.TextField()),
                ("CV_string_url", models.TextField()),
            ],
        ),
    ]
