# Generated by Django 4.1.7 on 2023-04-05 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0006_uservisit"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
        migrations.DeleteModel(name="UserInput",),
        migrations.RemoveField(model_name="deaninfo", name="school_class",),
        migrations.AddField(
            model_name="deaninfo",
            name="school_category",
            field=models.CharField(
                choices=[
                    ("econ", "economics"),
                    ("life", "life_science"),
                    ("chem", "chemistry"),
                    ("phys", "physics"),
                    ("macs", "math&computer_science"),
                    ("soci", "sociology"),
                    ("pol", "poliscience"),
                    ("gov", "govmanagement"),
                ],
                default="na",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="deaninfo",
            name="whether_oversea_phd",
            field=models.CharField(
                choices=[(1, "是"), (0, "否")], default="na", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="deaninfo",
            name="gender",
            field=models.CharField(
                choices=[("female", "女"), ("male", "男")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="deaninfo",
            name="year_phd_graduation",
            field=models.CharField(
                default="0000",
                max_length=4,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        message="Only xxxx are allowed.", regex="^[0-9]{4}$"
                    ),
                ],
            ),
        ),
    ]
