# Generated by Django 4.1.7 on 2023-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0007_delete_post_delete_userinput_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deaninfo",
            name="university_category",
            field=models.CharField(
                choices=[
                    ("985", "985"),
                    ("211", "211"),
                    ("985&211", "985&211"),
                    ("none", "none"),
                ],
                default="na",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="deaninfo",
            name="is_name_common",
            field=models.CharField(choices=[(1, "是"), (0, "否")], max_length=20),
        ),
        migrations.AlterField(
            model_name="deaninfo",
            name="university",
            field=models.CharField(
                choices=[
                    ("Xiamen University", "厦门大学"),
                    ("Suzhou University", "苏州大学"),
                    ("Zhongshan University", "中山大学"),
                    ("Fudan University", "复旦大学"),
                    ("Nankai University", "南开大学"),
                    ("Peking University", "北京大学"),
                    ("Langzhou Univesity", "兰州大学"),
                    ("Hunan University", "湖南大学"),
                    ("Southwest University", "西南大学"),
                    ("Sichuan University", "四川大学"),
                    ("Jilin University", "吉林大学"),
                    ("Zhejiang University", "浙江大学"),
                    ("Wuhan University", "武汉大学"),
                    ("Shandong University", "河南大学"),
                    ("University of Science and Technology of China", "中国科技大学"),
                ],
                default="na",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="UserVisit",),
    ]
