# Generated by Django 4.1.7 on 2023-04-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0009_alter_deaninfo_is_name_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deaninfo", name="CV_string_url", field=models.URLField(),
        ),
    ]
