# Generated by Django 3.2.25 on 2024-11-24 22:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_auto_20241123_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('econ', '经济'), ('soci', '社会学'), ('pol', '政府管理与政治学'), ('law', '法学')], max_length=50, verbose_name='学科大类'),
        ),
    ]
