# Generated by Django 3.2.25 on 2024-11-23 13:21

from django.db import migrations
import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_alter_schoolinfo_school_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_category',
            field=roster.models.SQLiteMultiSelectField(blank=True, choices=[('life', '生命科学'), ('chem', '化学'), ('phys', '物理'), ('macs', '数学与计算科学'), ('econ', '经济'), ('soci', '社会学'), ('pol', '政府管理与政治学'), ('law', '法学')], max_length=50, verbose_name='学科大类'),
        ),
    ]
