# Generated by Django 3.2.25 on 2024-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_alter_schoolinfo_school_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='学科名称')),
            ],
            options={
                'verbose_name': '学科大类',
                'verbose_name_plural': '学科大类',
            },
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='school_category',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='school_category',
            field=models.ManyToManyField(blank=True, to='roster.SchoolCategory', verbose_name='学科大类'),
        ),
    ]
